### ISSUE TITLE
使用docker compose部署失败

### ISSUE THREAD

**Issue by wxhuang** [cnpm/cnpmjs.org#1657]
```shell
$ docker-compose up
...
web_1       | /var/app/cnpmjs.org/config/config.js:131
web_1       |   nfs: require('fs-cnpm')({
web_1       |                          ^
web_1       | 
web_1       | TypeError: Class constructor LocalDiskClient cannot be invoked without 'new'
web_1       |     at Object.<anonymous> (/var/app/cnpmjs.org/config/config.js:131:26)
web_1       |     at Module._compile (internal/modules/cjs/loader.js:999:30)
web_1       |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
web_1       |     at Module.load (internal/modules/cjs/loader.js:863:32)
web_1       |     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
web_1       |     at Module.require (internal/modules/cjs/loader.js:887:19)
web_1       |     at require (internal/modules/cjs/helpers.js:74:18)
web_1       |     at Object.<anonymous> (/var/app/cnpmjs.org/config/index.js:355:10)
web_1       |     at Module._compile (internal/modules/cjs/loader.js:999:30)
web_1       |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
cnpmjsorg_web_1 exited with code 1
```
这个问题我提交[PR](https://github.com/cnpm/cnpmjs.org/pull/1656)了，麻烦处理一下。

**Comment by wxhuang** [comment]
#1656

**Comment by xzt427** [comment]
请问解决了吗？我也遇到了这个问题

**Comment by xx-zhang** [comment]
配置 
```
version: '2'
services:
  web:
    image: registry.cn-hangzhou.aliyuncs.com/rapid7/cnpmjs
    container_name: cnpmjs
    depends_on:
      - mysql-db
    volumes:
      - ./docs/dockerize/config.js:/var/app/cnpmjs.org/config/config.js
      - /srv/docker/cnpm-files:/var/data/cnpm_data
    ports:
      - "7001:7001"
      - "7002:7002"

  mysql-db:
    image: registry.cn-hangzhou.aliyuncs.com/rapid7/mysql56
    container_name: mysql-db
    restart: always
    ports:
      - 3306:3306
    environment :
      #MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: cnpmjs_test
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./docs/db.sql:/docker-entrypoint-initdb.d/cnpm-init.sql
      - /srv/docker/cnpm-db:/var/lib/mysql
```


在 ./docs/dockerize/config.js 中注释了这几行，解决了问题，nfs的挂载不需要再这个里面进行，在外面一样。
